# Generated by Django 5.1.4 on 2024-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_message_plain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='plain_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
