# Generated by Django 5.1.4 on 2024-12-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='plain_text',
        ),
    ]
