# Generated by Django 5.1.4 on 2024-12-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_message_plain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='plain_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
