# Generated by Django 5.1.4 on 2024-12-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_message_sender_username_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_username_encrypted',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=255),
        ),
    ]
